paths:
  /agendamento:
    get:
      tags:
      - Agendamento 
      summary: Listar todas as consultas marcadas de acordo com o dia
      produces:
      - application/json
      responses:
        405:
          description: Entrada invalida
        200:
          description: Array das consultas marcadas

  /andemaneto/agendar:
    post:
      tags:
        - Agenda
      summary: Agendar uma nova consulta para o paciente
      produces:
        - applicaton/json
      parameters:
        - name: Consultas
          description: Consultas Object
          in: body
      responses:
        200:
          description: Consulta marcada com sucesso
  /consulta/updade/{idConsulta}:
    put:
      tags:
        - Consulta
      summary: Alterar os dados de uma consulta cadastrado
      produces:
        - applicaton/json
      parameters:
        - name: idConsulta
          description: Consulta id
          in: path
          require: true
      responses:
        200:
          description: Alterado com sucesso
  /consulta/cancel/{idConsulta}:
      put:
        tags:
          - Consulta
        summary: Cancelar uma consulta cadastrada
        produces:
          - applicaton/json
        parameters:
          - name: idConsulta
            description: Consulta id
            require: true
            in: path
        responses:
          200:
            description: Cancelada com sucesso
  /consulta/find/{idConsulta}:
      get:
        tags:
          - Consulta
        summary: Retornar os dados de uma consulta marcada
        produces:
          - applicaton/json
        parameters:
          - name: idConsulta
            description: Supervisor id
            require: true
            in: path
        responses:
          200:
            description: Listado com sucesso 